# Generated by Django 5.2.1 on 2025-06-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_details',
            name='assigned_to',
        ),
    ]
